---
title: "Untitled"
author: "Joshua McCarthy"
date: "30/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


# Getting Data

```{r, eval = FALSE}
download.file("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv", "./data/covid_owid.csv")
```
```{r}
covid <- read.csv("./data/covid_owid.csv")
```

```{r}
#tests

tests <- covid %>% 
  filter(new_tests_smoothed_per_thousand >= 0)

unique(tests$location)

# cases

cases <- covid %>% 
  filter(new_cases_per_million >= 0)

unique(cases$location)

# deaths

deaths <- covid %>% 
  filter(new_deaths_per_million >= 0)

unique(deaths$location)
```

```{r}
deaths <- covid %>% 
  filter(total_deaths >= 5, location != "World", location != "International") %>% 
  group_by(iso_code) %>% 
  mutate(sincefive = row_number(), maxdeath = max(total_deaths)) %>% 
  filter(maxdeath >=2500) %>% 
  ungroup() %>% 
  filter(iso_code != "USA", iso_code != "ESP")

ggplot(deaths, aes(x = sincefive, y = total_deaths, color = iso_code)) + geom_line()+ theme(legend.position = "none")

ggplot(deaths, aes(x = sincefive, y = new_deaths_per_million, color = iso_code)) + geom_line() + geom_smooth()+ theme(legend.position = "none")
```

